sudo: required

services:
  - docker

before_install:
  - docker build -t bgahavan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bgahavan/react-test npm test

after_success:
  - docker build -t bgahavan/multi-client ./client
  - docker build -t bgahavan/multi-nginx ./nginx
  - docker build -t bgahavan/multi-server ./server
  - docker build -t bgahavan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bgahavan/multi-client
  - docker push bgahavan/multi-nginx
  - docker push bgahavan/multi-server
  - docker push bgahavan/multi-worker
